namespace GenieLib
{
    // https://github.com/dderevjanik/agescx-js/blob/master/packages/data/Unit.ts
    public enum AoeEntityType
    {
        Academy = 0,
        Alligator = 1,
        Bowman = 4,
        ImprovedBowman = 5,
        CompositeBowman = 6,
        Discovery = 10,
        Ballista = 11,
        Barracks = 12,
        FishingBoat = 13,
        TradeBoat = 15,
        MerchantShip = 16,
        LightTransport = 17,
        HeavyTransport = 18,
        ScoutShip = 19,
        WarGalley = 20,
        Trireme = 21,
        ElephantArcher = 25,
        StoneThrower = 35,
        Catapult = 36,
        Cavalry = 37,
        HeavyCavalry = 38,
        HorseArcher = 39,
        Chariot = 40,
        ChariotArcher = 41,
        Dock = 45,
        WarElephant = 46,
        Elephant = 48,
        SiegeWorkshop = 49,
        Farm = 50,
        FishTuna = 52,
        FishSalmon = 53,
        // Hero? = 58
        BerryBush = 59,
        LionTame = 60,
        // Hero? = 62
        // Hero? = 63
        Gazelle = 65,
        GoldMine = 66,
        Granary = 68,
        GuardTower = 69,
        House = 70,
        SmallWall = 72,
        Clubman = 73,
        Axeman = 74,
        ShortSwordsman = 75,
        BroadSwordsman = 76,
        LongSwordsman = 77,
        // Hero? = 78
        WatchTower = 79,
        // Hero? = 81
        GovernmentCenter = 82,
        Villager = 83,
        Market = 84,
        ArcheryRange = 87,
        LionKing = 89,
        ElephantKing = 90,
        Hoplite = 93,
        Phalanx = 94,
        Eagle = 96,
        Stable = 101,
        StoneMine = 102,
        StoragePit = 103,
        Temple = 104,
        WarChest = 108,
        TownCenter = 109,
        Flare = 112,
        MediumWall = 117,
        Priest = 125,
        Lion = 126,
        Fortification = 155,
        Ruins = 158,
        Artifact = 159,
        DoublePoleFlag = 162,
        SentryTower = 199,
        // Hero? = 227
        BlindLamePriest = 228,
        InvisibleDemon = 229,
        // Hero? = 230
        // Hero? = 231
        // Hero? = 233
        Mercenary = 240,
        // Hero? = 245
        CatapultTrireme = 250,
        FishShore1 = 260,
        FishShore2 = 263,
        Wonder = 276,
        Juggernaught = 277,
        BallistaTower = 278,
        Helepolis = 279,
        HeavyCatapult,
        HeavyHorseArcher = 281,
        Legion = 282,
        Cataphract = 283,
        Centurion = 291,
        Raft = 292,
        FlyingDutchman = 297,
        Medusa = 298,
        Scout = 299,
        SinglePoleFlag = 330,
        CamelRider = 338,
        ScytheChariot = 339,
        ArmoredElephant = 345,
        Slinger = 347,
        FireGalley = 360,
        AlligatorKing = 362,
        FishWhale = 370,
        // Hero? = 375
        // Hero? = 376
        CleopatrasBarge = 377,
        // Hero? = 378
        // Hero? = 379
        ZenobiasTower = 380,
        // Hero? = 381
        // Hero? = 382
        MirrorTower = 383,
        GazelleKing = 384,
        BeachArticles = 385,

        /*fish = 260,
        Cliff1 = 264,
        Cliff2,
        Cliff3,
        Cliff4,
        Cliff5,
        Cliff6,
        Cliff7,
        Cliff8,
        Cliff9,
        Cliff10,*/
    }
}